# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'merger.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 391))
        self.centralwidget.setObjectName("centralwidget")
        self.select = QtWidgets.QPushButton(self.centralwidget)
        self.select.setGeometry(QtCore.QRect(50, 30, 300, 80))
        self.select.setMaximumSize(QtCore.QSize(300, 80))
        self.select.setBaseSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(25)
        self.select.setFont(font)
        self.select.setObjectName("select")
        self.merge = QtWidgets.QPushButton(self.centralwidget)
        self.merge.setGeometry(QtCore.QRect(50, 130, 300, 80))
        self.merge.setMaximumSize(QtCore.QSize(300, 80))
        self.merge.setBaseSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(25)
        self.merge.setFont(font)
        self.merge.setObjectName("merge")
        self.progress = QtWidgets.QProgressBar(self.centralwidget)
        self.progress.setEnabled(True)
        self.progress.setGeometry(QtCore.QRect(-10, 360, 451, 23))
        self.progress.setMaximumSize(QtCore.QSize(500, 16777215))
        self.progress.setProperty("value", 0)
        self.progress.setObjectName("progress")
        self.labelProgress = QtWidgets.QLabel(self.centralwidget)
        self.labelProgress.setGeometry(QtCore.QRect(-10, 330, 421, 31))
        self.labelProgress.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(15)
        font.setUnderline(False)
        font.setStrikeOut(False)
        font.setKerning(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.labelProgress.setFont(font)
        self.labelProgress.setScaledContents(True)
        self.labelProgress.setAlignment(QtCore.Qt.AlignCenter)
        self.labelProgress.setObjectName("labelProgress")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF Merger"))
        self.select.setText(_translate("MainWindow", "Select files"))
        self.merge.setText(_translate("MainWindow", "Merge"))
        self.labelProgress.setText(_translate("MainWindow", "No files selected"))
