# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tableEditor(object):
    def setupUi(self, tableEditor):
        tableEditor.setObjectName("tableEditor")
        tableEditor.resize(200, 181)
        self.centralwidget = QtWidgets.QWidget(tableEditor)
        self.centralwidget.setObjectName("centralwidget")
        self.rowsCount = QtWidgets.QLabel(self.centralwidget)
        self.rowsCount.setGeometry(QtCore.QRect(20, 40, 55, 16))
        self.rowsCount.setObjectName("rowsCount")
        self.columnCount = QtWidgets.QLabel(self.centralwidget)
        self.columnCount.setGeometry(QtCore.QRect(20, 70, 55, 16))
        self.columnCount.setObjectName("columnCount")
        self.rowsCounter = QtWidgets.QSpinBox(self.centralwidget)
        self.rowsCounter.setGeometry(QtCore.QRect(100, 40, 42, 22))
        self.rowsCounter.setMinimum(1)
        self.rowsCounter.setObjectName("rowsCounter")
        self.columnCounter = QtWidgets.QSpinBox(self.centralwidget)
        self.columnCounter.setGeometry(QtCore.QRect(100, 70, 42, 22))
        self.columnCounter.setMinimum(1)
        self.columnCounter.setObjectName("columnCounter")
        self.create = QtWidgets.QPushButton(self.centralwidget)
        self.create.setGeometry(QtCore.QRect(50, 140, 101, 28))
        self.create.setObjectName("create")
        self.paddingCounter = QtWidgets.QSpinBox(self.centralwidget)
        self.paddingCounter.setGeometry(QtCore.QRect(100, 100, 42, 22))
        self.paddingCounter.setMinimum(1)
        self.paddingCounter.setObjectName("paddingCounter")
        self.cellPadding = QtWidgets.QLabel(self.centralwidget)
        self.cellPadding.setGeometry(QtCore.QRect(20, 100, 81, 16))
        self.cellPadding.setObjectName("cellPadding")
        self.name = QtWidgets.QLabel(self.centralwidget)
        self.name.setGeometry(QtCore.QRect(20, 10, 55, 16))
        self.name.setObjectName("name")
        self.tableName = QtWidgets.QLineEdit(self.centralwidget)
        self.tableName.setGeometry(QtCore.QRect(70, 10, 113, 22))
        self.tableName.setObjectName("tableName")
        tableEditor.setCentralWidget(self.centralwidget)

        self.retranslateUi(tableEditor)
        QtCore.QMetaObject.connectSlotsByName(tableEditor)

    def retranslateUi(self, tableEditor):
        _translate = QtCore.QCoreApplication.translate
        tableEditor.setWindowTitle(_translate("tableEditor", "Table Editor"))
        self.rowsCount.setText(_translate("tableEditor", "Rows:"))
        self.columnCount.setText(_translate("tableEditor", "Columns:"))
        self.create.setText(_translate("tableEditor", "Create"))
        self.cellPadding.setText(_translate("tableEditor", "Cell padding:"))
        self.name.setText(_translate("tableEditor", "Name:"))
