name: Python-Build-Release
on: [push]
jobs:
  Python-Build-Release:
   runs-on: windows-2019
   steps:
     - name: Checkout Project
       uses: actions/checkout@v3

     - name: Setup Python
       uses: actions/setup-python@v4
       with:
        python-version: '3.11.2'

     - name: Install Dependencies
       run: pip install -r ./src/requirements.txt

     - name: Create Build
       run: pyinstaller ./src/main.py --onefile --name PDFy --noconsole --add-data "src/pdf2htmlex/;pdf2htmlex/"

     - name: Create Folder
       run: mkdir main-app

     - name: Copy EXE files
       run: xcopy dist\PDFy.exe main-app\

     - name: Copy Data
       run: xcopy src\pdf2htmlex main-app\pdf2htmlex\ /E/H/C/I
    
     - name: Copy LICENSE
       run: xcopy LICENSE main-app\

     - name: Remove EXE
       run: del main-app\pdf2htmlex\pdf2htmlEX.exe

     - name: Create Archive
       run: tar -c -f main-app.tar main-app

     - name: Create Release
       id: create_release
       uses: actions/create-release@v1
       env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
        tag_name: V${{ github.RUN_NUMBER }}
        release_name: Release V${{ github.RUN_NUMBER }}
        draft: false
        prerelease: false

     - name: Upload Release Asset 
       uses: actions/upload-release-asset@v1
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       with:
         upload_url: ${{ steps.create_release.outputs.upload_url }}
         asset_path: main-app.tar
         asset_name: main-app.tar
         asset_content_type: archive/tar
  